
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rent_manager?serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql

#mybatis:
#  mapper-locations: classpath*:com/rent/manager/mapper/xml/*.xml