spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentmange?serverTimezone=GMT%2B8&amp;useSSL=false
    data-username: root
    data-password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.rent.rent.model
  configuration:
    map-underscore-to-camel-case: true
